---
- name: restart nginx
  become: yes
  systemd: name=nginx state=restarted

- name: touch osmcards
  file:
    path: /opt/src/osmcards/osmcards.wsgi
    state: touch

- name: restart supervisord
  become: yes
  systemd: name=supervisor state=restarted
