---
- name: restart nginx
  become: yes
  systemd: name=nginx state=restarted

- name: restart supervisord
  become: yes
  systemd: name=supervisor state=restarted

- name: restart uwsgi
  become: yes
  supervisorctl:
    name: osmcards
    state: restarted
