---
- name: Create MySQL database
  mysql_db:
    name: osmcards
    state: present

- name: Create MySQL user
  mysql_user:
    - host: localhost
    - name: osmcards
    - password: "{{ mysql_osmcards_password }}"
    - priv: osmcards.*:ALL
    - state: present

- name: Migrate the database
  environment:
    FLASK_APP: /opt/src/osmcards/www
  command: /opt/src/osmcards/venv/bin/flask migrate
  register: db_migrate
  changed_when: not db_migrate.stdout
