---
- name: Checkout osmcards
  git:
    repo: https://github.com/Zverik/osmcards.git
    dest: /opt/src/osmcards
  notify: restart uwsgi

- name: Upload osmcards config
  template:
    src: config.py.tmpl
    dest: /opt/src/osmcards/config.py

- name: Install virtualenv
  become: yes
  apt:
    name:
      - python3-virtualenv
      - python3-dev
    state: present

- name: Create virtualenv
  pip:
    requirements: /opt/src/osmcards/requirements.txt
    virtualenv: /opt/src/osmcards/venv
    virtualenv_python: python3.8

- name: Init the database
  import_tasks: db.yml

- name: Set up nginx and uwsgi
  import_tasks: nginx_uwsgi.yml
