---
- name: Install transifex
  become: yes
  unarchive:
    src: https://github.com/transifex/cli/releases/download/v1.6.10/tx-linux-amd64.tar.gz
    remote_src: true
    dest: /usr/local/bin
    include: [tx]
    creates: /usr/local/bin/tx

- name: Upload transifex configuration
  template:
    src: transifexrc
    dest: "/home/{{ ansible_user }}/.transifexrc"

- name: Download translations
  command: tx pull -a
  args:
    chdir: /opt/src/osmcards
  register: tx_pull
  changed_when: "'] - Done' in tx_pull.stdout"
  tags: osmcards

- name: Looking for po files
  when: tx_pull is changed
  find:
    paths: /opt/src/osmcards/www/translations
    patterns: messages.po
    file_type: file
    # age: 1h
    recurse: yes
  register: new_translations
  tags: osmcards

- name: Remove fuzzy marker
  when: new_translations.files is not undefined
  replace:
    path: "{{ item.path }}"
    regexp: "^#.*fuzzy"
    replace: ''
  loop: "{{ new_translations.files }}"
  tags: osmcards

- name: Compile messages
  when: new_translations.files is not undefined
  command: /opt/src/osmcards/venv/bin/pybabel compile -d /opt/src/osmcards/www/translations
  tags: osmcards
  notify: restart uwsgi
