---
- hosts: localhost
  vars:
    galaxy_path: roles.galaxy
  tasks:
    - name: Remove old galaxy roles
      file: path={{ galaxy_path }} state=absent
    - name: Install Ansible Galaxy roles
      local_action: command ansible-galaxy install -r requirements.yml --roles-path {{ galaxy_path }}
