---
- hosts: all
  gather_facts: no
  become: yes
  remote_user: root
  roles:
    - common

- hosts: all
  become: yes
  remote_user: root
  roles:
    - role: oefenweb.swapfile
      swapfile_size: 1GB
    - geerlingguy.ntp
    - geerlingguy.mysql
    - backup
    - { role: geerlingguy.certbot, tags: certbot }
    - nginx
    - firewall

- hosts: all
  remote_user: zverik
  vars:
    ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  roles:
    - { role: osmcards, tags: osmcards }

- hosts: localhost
  gather_facts: no
  tasks:
    - name: Test connection to OSM Cards
      uri:
        url: https://osmcards.org/
        status_code: 200
      tags: osmcards
